# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_reviews_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='juror',
        ),
    ]
