# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_reviews_juror'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='juror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
